[versions]
koin = "4.1.1"

[libraries]
xlog = "com.elvishew:xlog:1.11.1"

ratingbar = "me.zhanghai.android.materialratingbar:library:1.4.0"
composeRatingbar = "com.github.a914-gowtham:compose-ratingbar:1.3.12"

versionsx = "com.github.ben-manes:gradle-versions-plugin:0.51.0"

sqlcipher = "net.zetetic:sqlcipher-android:4.12.0"

exifinterface = "androidx.exifinterface:exifinterface:1.3.7"

dropbox-core = "com.dropbox.core:dropbox-core-sdk:7.0.0"
dropbox-android = "com.dropbox.core:dropbox-android-sdk:7.0.0"

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

zxing-android-embedded = "com.journeyapps:zxing-android-embedded:4.3.0"
